#!/usr/bin/env bash
# Install nginx on your web-01 server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page)

apt-get update
apt-get install -y nginx
mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World" > /etc/nginx/html/index.html
printf %s "server {
        root        /etc/nginx/html;
        index       index.html index.htm;
        listen      80 default_server;
        listen      [::]:80 default_server;
}
" > /etc/nginx/sites-available/default
service nginx restart 
